### ISSUE TITLE
Panic During Operation

### ISSUE THREAD

**Issue by bonedaddy** [bonedaddy/go-indexed#17]
```
2021/01/01 11:44:56 bot is now running
panic: runtime error: index out of range [0] with length 0

goroutine 29 [running]:
github.com/bonedaddy/go-indexed/bindings/uniswapv2/pair.(*Uniswapv2pairCaller).GetReserves(0xc0000ae5f0, 0xc000a77cf0, 0x2540be400, 0xecf0a0, 0xc0005cd1a0, 0xc000479b50, 0x0)
	/BUILD/bindings/uniswapv2/pair/v2pair.go:408 +0x1de
github.com/bonedaddy/go-indexed/uniswap.(*Client).GetReserves(0xc0000aec18, 0x8dfe23b239aa2ac0, 0x8d9ea274f5c0e0a, 0x7454176bc26c753c, 0x958ba94dc49490e8, 0xf1d2795c4eaed4e, 0x0, 0x0, 0x0)
	/BUILD/uniswap/client.go:52 +0x176
github.com/bonedaddy/go-indexed/bclient.(*Client).Reserves(0xc0004212d0, 0xd9a0ef, 0x7, 0xc26c753c08d9ea00, 0x0, 0x0)
	/BUILD/bclient/uniswap.go:110 +0x20c
github.com/bonedaddy/go-indexed/bclient.(*Client).EthDaiPrice(0xc0004212d0, 0xc0004810a0, 0x12, 0xc000481700)
	/BUILD/bclient/uniswap.go:87 +0x45
github.com/bonedaddy/go-indexed/bclient.(*Client).NdxDaiPrice(0xc0004212d0, 0x3, 0xc00053e3ca, 0x3)
	/BUILD/bclient/uniswap.go:35 +0xc9
github.com/bonedaddy/go-indexed/discord.launchWatchers.func1(0xc000430710, 0xc00044e6c0, 0xecf020, 0xc00030b140, 0xc0004212d0, 0xc0004306c0, 0x3)
	/BUILD/discord/discord.go:229 +0x6cf
created by github.com/bonedaddy/go-indexed/discord.launchWatchers
	/BUILD/discord/discord.go:192 +0x1b2
```

**Comment by bonedaddy** [comment]
fixed by upgrading abigen
